<?php
/**
 * Created by PhpStorm.
 * User: Paruryan
 * Date: 9/16/14
 * Time: 3:19 AM
 */



class ListView2 extends \CListView {
    public function init()
    {
       // parent::$cssFile =
        parent::init();
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }


} 